server {
    listen 80;
    server_name localhost;

    # Η ρίζα του server: Πρέπει να ταιριάζει με τον προορισμό του COPY
    root /usr/share/nginx/html;

    # Το αρχείο που φορτώνει ο browser
    index index.html index.htm;

    location / {
        # Αυτό είναι κρίσιμο για τις Angular εφαρμογές: αν δεν βρεθεί το αρχείο, επιστρέφει το index.html
        try_files $uri $uri/ /index.html;
    }

    # Μπορείς να προσθέσεις εδώ και τη ρύθμιση proxy_pass για το backend
    # Για παράδειγμα:
    # location /api/ {
    #     proxy_pass http://backend:8000;
    # }
}