server {
    listen 80;
    server_name localhost;

    # Η ρίζα (root) του server, όπου ψάχνει για τα αρχεία.
    # Πρέπει να ταιριάζει με τον προορισμό της εντολής COPY.
    root /usr/share/nginx/html;

    # Δείχνουμε στο Nginx ποια αρχεία να ψάξει πρώτα.
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Μπορείς να προσθέσεις εδώ και τη ρύθμιση proxy_pass για το backend
}